#!/bin/bash

# Capture $DOCKER_IMAGE from the ARGV
DOCKER_IMAGE=$1

# Get the IMAGE via docker pull if not present locally
answer=`docker image inspect $DOCKER_IMAGE --format="yes"`
echo "Answer is:$answer"

if [ $answer ]; then
  echo "Found $IMAGE_NAME locally"
else
  echo "# Pulling ${DOCKER_IMAGE}"
  echo "#"
  docker pull $DOCKER_IMAGE
fi;

# Replace ':' by '-'
SING_IMAGE=${DOCKER_IMAGE//:/-}

# Split by `/` to get the actual name
arr=(${SING_IMAGE//\// })
SING_IMAGE=${arr[1]}

echo "# new name: ${SING_IMAGE}"
echo "# will run: "
echo "#   docker save ${DOCKER_IMAGE}  -o  ./${SING_IMAGE}.tar"
echo "#   singularity build ${SING_IMAGE}.sif docker-archive://${SING_IMAGE}.tar"

docker save ${DOCKER_IMAGE}  -o ./${SING_IMAGE}.tar
singularity build ${SING_IMAGE}.sif docker-archive://${SING_IMAGE}.tar

# Build a sandbox
echo "# Will run: "
echo "#   singularity build  --fix-perms --sandbox ${SING_IMAGE}_sandbox  docker-archive://${SING_IMAGE}.tar"
echo "#   tar -cf ${SING_IMAGE}_sandbox.tar ${SING_IMAGE}_sandbox"

singularity build  --fix-perms --sandbox ${SING_IMAGE}_sandbox  docker-archive://${SING_IMAGE}.tar
tar -cf ${SING_IMAGE}_sandbox.tar ${SING_IMAGE}_sandbox

# Remove the tar file and sandbox directory:
echo "Will remove: ${SING_IMAGE}.tar ${SING_IMAGE}_sandbox"
rm ${SING_IMAGE}.tar
rm ${SING_IMAGE}_sandbox
